#!/usr/bin/env bash

FILES=$(gitamine f:c | grep "\.php$" | tr '\r\n' ' ')
LINES=${#FILES}

if [ "$LINES" -gt "1" ]
then
    eval bin/phpcbf --standard=PSR2 "${FILES}"
    eval bin/phpcs --standard=PSR2 "${FILES}"
fi
