#!/usr/bin/env bash

FILES=$(gitamine f:c | grep "\.php$" | tr '\r\n' ' ')
LINES=${#FILES}

if [ "$LINES" -gt "1" ]
then
    echo bin/phpcbf --standard=PSR2 "${FILES}"
    echo bin/phpcs --standard=PSR2 "${FILES}"
    exit 1
fi
