#!/usr/bin/env bash
#bin/console files:committed

BIN=phpunit;
MIN_COVERAGE=0

# The reading options part
while [[ $# -gt 0 ]] && [[ ."$1" = .--* ]] ;
do
    opt="$1";
    shift;              #expose next argument
    case "$opt" in
        "--" ) break 2;;
        "--bin="* )
           BIN="${opt#*=}";;
        "--enabled="* )
           continue;;
        "--min-coverage="* )
           MIN_COVERAGE="${opt#*=}";;
   esac
done

COMMAND="$BIN"

# If need to verify coverage
if [ "$MIN_COVERAGE" -gt "0" ]; then
    COMMAND="$COMMAND --coverage-text=.coverage"
fi

if eval "${COMMAND}"; then
    echo ''
else
    if [ "$MIN_COVERAGE" -gt "0" ]; then
        rm .coverage
    fi
    exit 1
fi

# Verifying if coverage has succeed
if [ "$MIN_COVERAGE" -gt "0" ]; then
    result=$(head -n9 .coverage | tail -n1 )

    arr=("${result}")
    result=${arr[1]}
    result=$(echo "$result" | cut -d '.' -f 1)

    rm .coverage

    if [ "$result" -lt "$MIN_COVERAGE" ]; then
        tput setb 1
        tput setaf 7
        printf " Coverage is below %s " "$MIN_COVERAGE"
        tput sgr0
        exit 1
    fi
fi

exit 0
