#!/usr/bin/env bash
#bin/console files:committed

BIN=phpunit;
MIN_COVERAGE=0
ENABLED=1

# The reading options part
while [[ $# -gt 0 ]] && [[ ."$1" = .--* ]] ;
do
    opt="$1";
    shift;              #expose next argument
    case "$opt" in
        "--" ) break 2;;
        "--bin="* )
           BIN="${opt#*=}";;
        "--enabled="* )
           ENABLED="${opt#*=}";;
        "--min-coverage="* )
           MIN_COVERAGE="${opt#*=}";;
        *) echo >&2 "Invalid option: $@"; exit 1;;
   esac
done

COMMAND="$BIN"


# If need to verify coverage
if [ "$MIN_COVERAGE" -gt "0" ]; then
    COMMAND="$COMMAND --coverage-text=cov"
fi

if eval "${COMMAND}"; then
    echo ''
else
    rm cov
    exit 1
fi

# Verifying if coverage has succeed
if [ "$MIN_COVERAGE" -lt "0" ]; then
    result=$(cat cov | head -n 9 | tail -n 1 )
    arr=(${result})
    result=${arr[1]}
    result=$(echo "$result" | cut -d '.' -f 1)

    rm cov;

    if [ "$result" -gt "$MIN_COVERAGE" ]; then
        printf "\033[41m\033[37m Coverage is below $MIN_COVERAGE \033[0m\n\n"
        exit 1
    fi
fi

exit 0
